Util(validate, color) 등록했습니다.
todait/MyBaseballRecordClient pull request #18
Opened 2024-03-07 15:33 UTC by chepchep2

2024-03-07 15:33 UTC, chepchep2 commented
* **#18** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/18?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-11 02:14 UTC, flowkater commented on lib/common/auth_color.dart
> +  static const blackColor10 = Color(0x10000000);
피그마 네이밍 그대로 가져온거죠?

2024-03-11 02:16 UTC, flowkater commented on lib/common/auth_color.dart
파일 이름이 app_color.dart 로 바뀌어야할 것 같습니다.

2024-03-11 02:16 UTC, flowkater requested changes
코멘트 확인 부탁해요

2024-03-11 02:48 UTC, chepchep2 commented on lib/common/auth_color.dart
> +  static const blackColor10 = Color(0x10000000);
이 스택은 피그마 네이밍 그대로 가져온 것은 아니고 최신 스택에 피그마 네이밍을 사용했습니다.

2024-03-11 02:48 UTC, chepchep2 commented on lib/common/auth_color.dart
넵 수정하겠습니다.

2024-03-18 00:12 UTC, chepchep2 commented
### Merge activity

* **Mar 17, 8:12 PM EDT**: @chepchep2 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/18).

2024-03-18 00:12 UTC, merged