인트로페이지 버튼까지 작업, 아이콘은 아직입니다.
todait/MyBaseballRecordClient pull request #2
Opened 2024-03-04 10:11 UTC by chepchep2

2024-03-04 10:11 UTC, chepchep2 commented
* **#3** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/3?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/2?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-04 14:53 UTC, flowkater commented on lib/common/auth_button.dart
> +    return ElevatedButton(
ElevatedButton 을 쓰지 말고,
그냥 DecoratedBox 랑 GestureDetector 를 쓰는 방향으로 가면 좋을 것 같습니다.

```dart
GestureDetector(
        onTap: widget.onTap,
        child: DecoratedBox(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(32.0),
            border: Border.all(
              color: Colors.black,
            ),
            color: _isHovered ? Colors.black : Colors.white,
          ),
          child: Padding(
            padding: const EdgeInsets.symmetric(
              horizontal: 24.0,
              vertical: 18.0,
            ),
            child: Text(
              widget.buttonText,
              style: TextStyle(
                color: _isHovered ? Colors.white : Colors.black,
                fontSize: 16.0,
              ),
            ),
          ),
        ),
      ),
```

ElevatedButton 같은 기본 버튼은 머터리얼 스타일에 종속적이라서 권장하지 않는 방식입니다.

2024-03-04 14:53 UTC, flowkater requested changes
위 상황 한번 반영해주시면 좋을 것 같습니다.

2024-03-07 13:27 UTC, flowkater commented
### Merge activity

* **Mar 7, 8:27 AM EST**: @flowkater started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/2).

2024-03-07 13:28 UTC, merged