AuthButton 클릭시 효과 추가
todait/MyBaseballRecordClient pull request #23
Opened 2024-03-10 13:42 UTC by chepchep2

2024-03-10 13:43 UTC, chepchep2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/23?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/23?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#22** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/22?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/21?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#20** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/20?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#19** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/19?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#18** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/18?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-11 02:20 UTC, flowkater commented on lib/common/auth_button.dart
> +      onTapDown: (_) {
onTap 이 TapDown, TapUp 다 포함입니다. TapDown/TapUp은 지워주세요.

2024-03-11 02:23 UTC, flowkater commented on lib/common/auth_button.dart
> +      onTap: () {
onClick 을 받아서 onTap 에서 같이 실행할거라서 widget.onClick 여기로

2024-03-11 02:24 UTC, flowkater commented on lib/common/auth_button.dart
> +    final currentBorderColor =
color 를 여기다가 별도 정의하는 것보다 위젯에 두는게 나을 것 같습니다

2024-03-11 02:24 UTC, flowkater commented on lib/common/auth_button.dart
> +  bool isPressed = false;
elevated Button 처럼 버튼을 한번더 감싸는 위젯을 만드는 게 어떨까요?

2024-03-11 02:24 UTC, flowkater requested changes
위젯 리팩토링 시간내서 같이 한번 보시죠

2024-03-11 02:54 UTC, chepchep2 commented on lib/common/auth_button.dart
> +      onTapDown: (_) {
이 부분에 대해서 많이 생각을 해봤습니다만 해결점을 찾지 못해 이렇게 작성했습니다.
onTap 하나만 하면 isPressed의 상태를 어떻게 변경해야할까요??

2024-03-18 00:12 UTC, chepchep2 commented
### Merge activity

* **Mar 17, 8:12 PM EDT**: @chepchep2 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/23).

2024-03-18 00:27 UTC, merged