코드 리뷰 수정, pressedButton 생성, AuthButton 수정
todait/MyBaseballRecordClient pull request #24
Opened 2024-03-12 03:26 UTC by chepchep2

2024-03-12 03:27 UTC, chepchep2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/24?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/25?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#24** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/24?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#23** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/23?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/22?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/21?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#20** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/20?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#19** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/19?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#18** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/18?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-12 03:39 UTC, flowkater commented on ios/Runner/Info.plist
> +	<key>FLTEnableImpeller</key>
혹시 ios 에 뭐 추가한거 있으신가요?

2024-03-12 03:40 UTC, flowkater commented on lib/common/auth_button.dart
> +//여기서 부터 가안으로 코드 작성 해보겠습니다.
주석은 삭제

2024-03-12 03:40 UTC, flowkater commented on lib/common/auth_button.dart
> +                    fontSize: 15.0, letterSpacing: 0.2, color: textColor),
여기도 TextStyle 반영 상수로 바꿀 수 있을까요?

2024-03-12 03:41 UTC, flowkater commented on lib/common/auth_button.dart
> +// class AuthButton extends StatefulWidget {
안쓰는 코드 주석 삭제

2024-03-12 03:41 UTC, flowkater commented on lib/common/pressed_button.dart
> +      // onTap: () {
OnTap 이 제대로 반영이 되나요? 주석이 되어있는데

2024-03-12 03:42 UTC, chepchep2 commented
[image: 스크린샷 2024-03-12 12.42.17.png]
이 부분때매 코드 추가했습니다.

2024년 3월 12일 (화) 오후 12:40, flowkater ***@***.***>님이 작성:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In ios/Runner/Info.plist
> <https://github.com/team-stoodi/MyBaseballRecordClient/pull/24#discussion_r1520806743>
> :
>
> > @@ -45,5 +45,7 @@
>  	<true/>
>  	<key>UIApplicationSupportsIndirectInputEvents</key>
>  	<true/>
> +	<key>FLTEnableImpeller</key>
>
> 혹시 ios 에 뭐 추가한거 있으신가요?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/team-stoodi/MyBaseballRecordClient/pull/24#pullrequestreview-1930030535>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX644UITJZRRJMNC4VQI3ALYXZ2I7AVCNFSM6AAAAABEROCQ4WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMZQGAZTANJTGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-12 03:43 UTC, flowkater requested changes
제대로 동작하는 건지 확인이 필요하네요.

2024-03-12 03:45 UTC, chepchep2 commented
혹시 실행 안되실까요?
저는 수정 뒤에는 실행이 잘되는데 실행 안되시면 다시 한번 알아보겠습니다.

2024년 3월 12일 (화) 오후 12:43, flowkater ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
>
> 제대로 동작하는 건지 확인이 필요하네요.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/team-stoodi/MyBaseballRecordClient/pull/24#pullrequestreview-1930032916>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX644UOEMNZRA5JYKSIKSJ3YXZ2XFAVCNFSM6AAAAABEROCQ4WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMZQGAZTEOJRGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-18 00:12 UTC, chepchep2 commented
### Merge activity

* **Mar 17, 8:12 PM EDT**: @chepchep2 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/24).
* **Mar 17, 8:30 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/24) rebased this pull request as part of a merge.
* **Mar 17, 8:31 PM EDT**: @chepchep2 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/24).

2024-03-18 00:31 UTC, merged