레지스터 페이지 작업, 1차입니다.
todait/MyBaseballRecordClient pull request #3
Opened 2024-03-04 10:11 UTC by chepchep2

2024-03-04 10:11 UTC, chepchep2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/3?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/3?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/2?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-04 14:54 UTC, flowkater commented on lib/common/auth_text_input_widget.dart
> +  final TextEditingController _controller = TextEditingController();
TextEditingController 도 _isTextNotEmpty 도 State 를 밖에서 주입을 받으면 좋을 것 같고, 해당 Widget 은 Stateless 하게 유지하면 좋을 것 같습니다.

2024-03-04 14:55 UTC, flowkater commented on lib/common/auth_text_input_widget.dart
> +                onPressed: () {
이것도 함수를 주입 받으면 좋을 것 같습니다. 직접 setState 를 호출하기보다

2024-03-04 14:55 UTC, flowkater requested changes
위 상황 한번 반영 부탁드립니다.

2024-03-04 15:27 UTC, chepchep2 commented on lib/common/auth_text_input_widget.dart
> +  final TextEditingController _controller = TextEditingController();
네 다시 해보겠습니다.

2024-03-04 15:27 UTC, chepchep2 commented on lib/common/auth_text_input_widget.dart
> +                onPressed: () {
다시 해보겠습니다.

2024-03-07 13:27 UTC, flowkater commented
### Merge activity

* **Mar 7, 8:27 AM EST**: @flowkater started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/3).

2024-03-07 13:31 UTC, merged

2024-03-07 13:31 UTC, flowkater approved these changes