RegisterPage(focus, completeMessage)
todait/MyBaseballRecordClient pull request #35
Opened 2024-03-18 14:13 UTC by chepchep2

2024-03-18 14:14 UTC, chepchep2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/35?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#35** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/35?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#34** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/34?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-18 16:35 UTC, flowkater commented on lib/page/register_page.dart
> +                      onChanged: (String value) {
함수로 분리하면 좋을 것 같습니다.
```dart
setState(() {
  showFinalPassword = value == passwordController.text;
});
```

이렇게 리팩토링 하면 더 좋지 않을까요?

2024-03-18 16:37 UTC, flowkater requested changes
로직이 너무 덕지덕지 복잡해지는 것 같네요.
각 if 문마다 왜 그렇게 동작해야하는지 상세하게 설명해주시면 감사하겠습니다.
조금 더 코드 정리가 필요해보이네요.

2024-03-19 04:35 UTC, chepchep2 commented on lib/page/register_page.dart
> +                      onChanged: (String value) {
네 알겠습니다.

2024-04-07 14:24 UTC, chepchep2 commented
### Merge activity

* **Apr 7, 10:24 AM EDT**: @chepchep2 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/35).

2024-04-07 14:27 UTC, merged