레지스터 페이지 작업, 2차(StickBottomButton)
todait/MyBaseballRecordClient pull request #4
Opened 2024-03-04 14:11 UTC by chepchep2

2024-03-04 14:12 UTC, chepchep2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/4?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/4?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#3** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/3?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/2?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-04 14:56 UTC, flowkater commented on lib/common/sticky_bottom_button.dart
> +class StickyBottomButton extends StatefulWidget {
State 가 없는데 굳이 Stateful 로 만들 필요는 없을 것 같습니다.
왠만하면 공용으로 사용하는 Widget 은 Stateless 가 되면 좋을 것 같아요.

2024-03-04 14:56 UTC, flowkater requested changes
코드 참고 부탁드립니다.

2024-03-04 15:28 UTC, chepchep2 commented on lib/common/sticky_bottom_button.dart
> +class StickyBottomButton extends StatefulWidget {
참고하겠습니다

2024-03-07 13:27 UTC, flowkater commented
### Merge activity

* **Mar 7, 8:27 AM EST**: @flowkater started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/4).

2024-03-07 13:32 UTC, flowkater approved these changes

2024-03-07 13:34 UTC, merged