조건문을 private한 메서드로 만들고 widget으로 빼보았습니다.
todait/MyBaseballRecordClient pull request #62
Opened 2024-04-04 04:09 UTC by chepchep2

2024-04-04 04:09 UTC, chepchep2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/62?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#62** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/62?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#61** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/61?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#60** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/60?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#59** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/59?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#58** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/58?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#57** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/57?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#56** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/56?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#55** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/55?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#54** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/54?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#53** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/53?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#52** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/52?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#51** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/51?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#50** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/50?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#49** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/49?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#48** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/48?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#47** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/47?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#46** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/46?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#45** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/45?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#44** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/44?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#43** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/43?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#42** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/42?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#41** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/41?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#40** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/40?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#39** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/39?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#35** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/35?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#34** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/34?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/introPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-04 09:59 UTC, flowkater commented on lib/page/register_page.dart
> +    if (_passwordError.isNotEmpty) {
if 문이 위젯 안에 들어가는 건 별로 안좋은 것 같고, 굳이 Text 위젯을 이렇게까지 잘게 나눌 필요는 없을 것 같습니다.

아니면 한가지 방법은
_buildEmailInfoText 로 묶어서 Error 랑 정보 Text 랑 묶어서 노출을 하는 것도 한 방법일 것 같습니다.
email, password, confirmPassword 이렇게

함수를 나눌때 너무 잘게 쪼개는 것보다 목적별로 나누는게 좋을 것 같습니다.

그리고 Container() 보다 그냥 null 을 반환하면 에러가 나나요?

```dart
Widget _buildEmailErrorText() {
  return Visibility(
    visible: _emailError.isNotEmpty,
    child: Text(
      _emailError,
      style: AppTextStyle.caption213R.copyWith(
        color: AppColor.accentRed100,
      ),
    ),
  );
}
```

이런 식도 가능할 것 같고,
삼항 연산자로 null 을 반환하거나 SizedBox.shrink() 를 하는 것도 한 방법일 것 같습니다.

2024-04-04 10:00 UTC, flowkater requested changes
위 리뷰 참고부탁드립니다!

2024-04-07 14:24 UTC, chepchep2 commented
### Merge activity

* **Apr 7, 10:24 AM EDT**: @chepchep2 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/62).

2024-04-07 16:01 UTC, merged