UI 틀을 다시 잡았습니다.
todait/MyBaseballRecordClient pull request #75
Opened 2024-04-20 10:49 UTC by chepchep2

2024-04-20 10:49 UTC, chepchep2 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/75?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#75** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/75?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#74** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/74?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#73** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/73?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#72** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/72?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#71** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/71?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#70** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/70?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#69** <a href="https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/69?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/mainPage`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @chepchep2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-21 13:55 UTC, flowkater commented on lib/common/game_card.dart
> +  Widget getMatchStatus(BuildContext context) {
위젯 클래스 바깥으로 따로 분리해서 StatelessWidget 으로 만드는게 좋아보입니다.

아래 if 문은 

```dart
final now = DateTime.now();
  final today = DateTime(now.year, now.month, now.day);
  final tomorrow = today.add(const Duration(days: 1));
  final diff = matchDate.difference(today).inDays;

  final matchStartDateTime = DateTime(matchDate.year, matchDate.month, matchDate.day, startTime.hour, startTime.minute);
  final matchEndDateTime = DateTime(matchDate.year, matchDate.month, matchDate.day, endTime.hour, endTime.minute);

  if (matchDate.isBefore(today)) {
    return '';
  }

  if (matchDate == today && now.isAfter(matchStartDateTime) && now.isBefore(matchEndDateTime)) {
    return '진행중';
  }

  final formattedDate = DateFormat('M월 d일 E', 'ko_KR').format(matchDate);
  final formattedTime = _formatTime(startTime);

 if (diff == 0) {
  return '${_formatTime(startTime)} 시작';
} else if (diff == 1) {
  return '내일 $formattedDate • $formattedTime';
} else if (diff <= 100) {
  return 'D-$diff $formattedDate • $formattedTime';
} else {
  return '$formattedDate • $formattedTime';
}
```


위 코드 참고해서 리팩토링 하는게 좋아보입니다.
다만, 위젯을 반환해야한다면,
최종 상태값을 조건에 따라 반환하고 그 상태값에 맞는 위젯을 매핑해서 반환하는게 좋아보여요.


getMatchStatus -> enum 상태값만 return
enum 상태 값에 따라서 적절한 위젯을 _private function 으로 잘 쪼개서 반환

2024-04-21 13:56 UTC, flowkater commented on lib/common/game_card.dart
> +  List<Widget> getPositionChips(List<String> positions) {
이것도 위처럼 분리하는게 나아보입니다.

2024-04-21 13:57 UTC, flowkater commented on lib/page/main_page.dart
>    final List<GameCard> _upcomingGames = [
별로 파일로 빼면 좋을 것 같습니다. repository 등

2024-04-21 13:58 UTC, flowkater commented on lib/page/main_page.dart
> +                            ...filteredUpcomingGames.map((game) {
...todayGames 랑 ...filteredUpcomingGames 랑 만 다르고, 코드가 겹치는 것 같습니다.
private 위젯 함수로 분리하면 좋을 것 같습니다.

2024-04-21 13:59 UTC, flowkater commented on lib/page/main_page.dart
> +    final filteredUpcomingGames = sortedUpcomingGames
해당 값들은 전부 initState 에서 state 로 추후에는 셋업을 해주면 좋을 것 같습니다.
아직 UI 작업 중이라 그렇겠지만, 여기에 변수를 선언하면 UI가 업데이트될때마다 매번 새로 변수가 셋업이 됩니다.

2024-04-21 14:00 UTC, flowkater requested changes
일단 중간 과정을 거치는 코드들이 많아서 최종 브랜치에만 코드 리뷰 드립니다.
필요한 부분은 제가 코드를 받아서 다시 한번 찬찬히 살펴보겠습니다.

2024-05-15 11:11 UTC, flowkater commented
### Merge activity

* **May 15, 7:11 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/team-stoodi/MyBaseballRecordClient/75) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

2024-05-16 01:52 UTC, merged